### ISSUE TITLE
Perspective module does not install

### ISSUE THREAD

**Issue by cchorn** [timkpaine/lantern#157]
Everything will install except the following ...

jupyter labextension install @jpmorganchase/perspective

I've also tried to install the repo from source; this works and the labextension is enabled but if I run "lantern" commands in a notebook it produces this output "ImportError: No module named 'perspective'". (e.g., import lantern as l)

Any help would be appreciated. Thanks

**Comment by timkpaine** [comment]
You should install perspective-jupyterlab from source until there's a new release:

https://github.com/jpmorganchase/perspective/tree/master/packages/perspective-jupyterlab

Also make sure you have the dependencies, in particular perspective-python
https://github.com/timkpaine/lantern/blob/master/requirements.txt

**Comment by cchorn** [comment]
This works

Thank you

**Comment by timkpaine** [comment]
#158
