### ISSUE TITLE
plotly API key?

### ISSUE THREAD

**Issue by jealie** [timkpaine/lantern#174]
First of all, thumbs up for the great jupyter-lab extension :1st_place_medal: 

Plotly requires an API key to work (and a paid account make the plots private). I am wondering how the lantern extension handles this - is it using the offline version? If not, where are my plots visible online?

Thanks a bunch!

**Comment by timkpaine** [comment]
uses offline

**Comment by jealie** [comment]
So, to spell it out completely: my graphs are completely private when using lantern+plotly, is that right?

**Comment by timkpaine** [comment]
yep

**Comment by jealie** [comment]
That's great, thanks.
