### ISSUE TITLE
Cannot use lantern.grid with perspective. 

### ISSUE THREAD

**Issue by siddharthst** [timkpaine/lantern#180]
I'm trying to use the perspective to display some of my dataframes, but it just gives me an error : 
`Error displaying widget` - I'm not sure what is going wrong here. This is the output from `jupyter labextension list`
```
JupyterLab v0.35.4
Known labextensions:
   app dir: /anaconda3/share/jupyter/lab
        @jpmorganchase/perspective-jupyterlab v0.2.11  enabled  OK
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
        @jupyterlab/plotly-extension v0.18.1  enabled  OK
        ipysheet v0.2.0  enabled  OK
        jupyterlab_bokeh v0.6.3  enabled  OK
        lineup_widget v1.0.7  enabled  OK
        plotlywidget v0.6.0  enabled  OK
        pylantern v0.1.1  enabled  OK
        qgrid v1.1.1  enabled  OK
```

I can still use `grid()` with qgrid and others, just not with perspective.

**Comment by timkpaine** [comment]
Can you see what the error in the javascript console is? Most likely there's a version mismatch between the installed perspective-python package and the perspective jupyterlab extension

**Comment by siddharthst** [comment]
I'm not sure what you mean by javascript console, but it seems that you are right, there appears to be a mismatch between the perspective-python package and perspective lantern extension. A quick upgrade using pip solved the problem.

**Comment by DeepanshKhurana** [comment]
@siddharthst Did you manage to fix this? I'm running into the same issue, I guess.

``` manager.js:305 Uncaught (in promise) Error: Module @finos/perspective-jupyterlab, semver range ^0.3.0 is not registered as a widget module
    at WidgetManager.loadClass (manager.js:305)
    at WidgetManager.<anonymous> (manager-base.js:263)
    at step (manager-base.js:44)
    at Object.next (manager-base.js:25)
    at manager-base.js:19
    at new Promise (<anonymous>)
    at push.hs2k.__awaiter (manager-base.js:15)
    at WidgetManager.push.hs2k.ManagerBase._make_model (manager-base.js:257)
    at WidgetManager.<anonymous> (manager-base.js:246)
    at step (manager-base.js:44) 
```
...shows up in my JS console.

**Comment by siddharthst** [comment]
@DeepanshKhurana - I was able to fix the issue I had by reinstalling the packages. The issue you have might or might not have to do with the problem I had.
