### ISSUE TITLE
jupyterlab 1.0.0 support?

### ISSUE THREAD

**Issue by madsi1m** [timkpaine/lantern#187]
Hi will this be upgraded to work with jupyterlab 1.0.0 ??

**Comment by timkpaine** [comment]
yes

**Comment by timkpaine** [comment]
On second thought, I am deleting the jupyterlab extension:
https://github.com/timkpaine/lantern/pull/191

**Comment by timkpaine** [comment]
I am moving the `nbconvert hide code` facilities to https://github.com/timkpaine/jupyterlab_commands/tree/nbconvert
